const actionTypes = {
  CREATING_COURSE: 'CREATING_COURSE',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_COURSE_ERROR: 'CREATE_COURSE_ERROR',
  FETCH_COURSES: 'FETCH_COURSES',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_ERROR: 'FETCH_COURSES_ERROR',
};

export default actionTypes;
