const actionTypes = {
  CREATING_COURSE: 'CREATING_COURSE',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_COURSE_ERROR: 'CREATE_COURSE_ERROR',
  FETCH_COURSES: 'FETCH_COURSES',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_ERROR: 'FETCH_COURSES_ERROR',
  EDIT_COURSE: 'EDIT_COURSE',
  EDIT_COURSE_SUCCESS: 'EDIT_COURSE_SUCCESS',
  EDIT_COURSE_ERROR: 'EDIT_COURSE_ERROR',
  SET_ACTIVE_COURSE: 'SET_ACTIVE_COURSE',
};

export default actionTypes;
